language: java
install: mvn install -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
script: mvn package -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
env:
  global:
  - SONATYPE_USERNAME=onesuperclark
  - secure: jotelfD8Vdo7IWjU5ToEDk6PY/Ccdbf/phuRxk/v90rCPfkJ5lxFnY81anLocvQUSynLC+erIEzPPSYbq2NVv4x91snNL7qmzHnU57gTrXbYQiiIupHSoGDJHmIF22lApDmMWU2yayoG8YLUuWE13aQpxD2s3H/EwM6KuJMd48eNW18cWukj3M5uqABDvzGL+U8YIQP9Y4EhYLixqwAXHpnJQgqaTQ4B6mBQrHv60bIwep48K5iOPuAnznhNkRIbHKQzkxio2OCx/x6In8Dm6cgje9mHypcsYn2SyQ63D5KWWPFQhToUGSMLbjXUJJ+uYB1ZxnglhjbutaZ1/5Rd15fS/QpXyMGLK8OB8cnBxaQYhWmV2bAq837D0EQ2XCc7hRg9o7y8U6T0VzQ8hrGAXRKrXwfKHI12ymExRNWirCNHs7VFHV8Dd1CieMUrOvVm/KNEb7FQW+9NVYns4fEtJCQtcGCIEsERpIBPbQXXRAdJWmh9SniCQZaaCEhBCF8zXOYYBAPLQ1VeyBVUgKiJk7JUby4hV+RHe9f3dGDiy4NsS9ghR+YDwPhPZMgvcOH0jsPKLhFhnEAdex9JMKn1NVPAacKCpK5eselGRfm0BpKEgrZR0YVsfGdDSrSCDJG98Zq8112cdYVen3f8W+sSE8G5qInVleo4QVVheDjwKdw=
  - secure: mXiTTXbzP5Li+CN+6q4GgCIZvJbD1BF5563WSZIQytDAXnFY7p6RjLJievG8PhOxtVgjFy1tTHxSXSmF3n5zsBw5ydpkMh8/emBgqPTLuW0HgQ9rRGtQGno0ZYEDTSbLE/HxgyWpIuJ8FT9qQ2gCq6xRjNrGOBf2FwnohhCBMnQngeIOjenHNxMv19WlIzhVJfgjkRc01KGFEmytmF9+2oYH78Zf5ahj8SYJLsM13+Dtbgt34Lzc1ioxkegnnw4PpRp2cOZqisfHINl8K++OGdGYx79X9WCdga4lQLIpFg4HSrBBUp+ZB6qMa/O2hmclz8LoCx7h0ZPEPN3eiRPeZ3VR/JwnWMHqJnR77jljhV6DQ43ruWqpJu/1MZfW1F7Wlzz+UaRjcO6ATXDGRQB7bV+prMYTo8GnW9gZzgJ0G5zem422cL8yQgcwox+2fmVn0lH0k2jEJ9NYcWs/qGCyvkU7hZb4S8FJfFIeoA/tr9Hy4fLUQCWdQcF0Uh4tuvC/AaXkSv8Q/AmruoO4F3IB3+r9zkwG/q7Ah18GZamBrcGig9+xi+V54CJQWeAtpx9uCcW09BRmHBzJ7FxikIaQ816dn88BEO/vDXpVZDJYYocKiVFx9fo7dP7aZLAdkTEOjq6rmls98HGoxpkLaHOJztfj5mXs5l4Lpv1y3Lel114=
before_install:
- openssl aes-256-cbc -K $encrypted_7f0de2c50f2d_key -iv $encrypted_7f0de2c50f2d_iv
  -in secret.key.asc.enc -out secret.key.asc -d
before_deploy:
- export RELEASE_JARS=$(ls target/odps-jdbc-*.jar)
- echo "deploying RELEASE_JARS to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: XqVfGi6CVDo2xIJJ4N2fMtDUuaH5Zhk381mRKCaC+yKpzF9fEUVgthIqmRWzLeskNx1nsLMgVz5YlTqmxTZvmHHsbt8fDZj55hVTmFJn8d+/79P/I9Nh6MJL5+5gJvGCk2gjU7VyPQr/Xg1Pxb5IJfNswuPOCuWSto8ZjaFDRSETXwFFnLGdIv0w5JgZMQq2AOG/jPgfmY1xPjsbMoUB2mgG8NDcuZMSRKmhFFczRpYBG1PCvhM4uvnkaRWFyasPqKLI9Kz/Mrehk+nS8EHwS7/5DVSfsOV8zT0tK4m08p9eYo7TA/WHcbeKjciqaiHzFx2Mo3MhFEPC1XIQ36ZUJXUTi/eB5ZhzQSsSpIVPkEgWq6U3ELZck1ZFAv48w8sjupL0/FbRezCKS37A7HnKWaROAHA/4QksR3VkqCcHDw416FST0+2h0QX+yst1aWJfxLrz7y1AM0tm1RWYQLJi3jn+uTfuojpw+TWug65cHrbgWllC4CU41pPjSpMwgqtximYLSEacDjBwtxxmSrPjz3I5P06HEZ1pLkRddTwI4FI3AsSNhuo+JRF1WEUwVzCUjVLwn2SJtblzFfoTJYGnl9ZeHFy0nsTyXX6R6tvAck+4tJpA3zZc9NAmNIWaH8t9MUj+9Zi3Ggl7jvqOyyIJoSbNPv3ttESkyl0okt0YZzg=
  file_glob: true
  file: target/odps-jdbc-*.jar
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- echo "deploying to maven central"
- gpg --import secret.key.asc
- mvn deploy --settings settings.xml -DskipTests=true -Dgpg.passphrase=$GPG_PASSPHRASE
